[package]
name = "rotor"
description = """
    The mio-based framework for doing I/O in simple and composable way
"""
license = "MIT"
readme = "README.rst"
keywords = ["io", "loop", "state", "machine", "mio"]
homepage = "http://github.com/tailhook/rotor"
version = "0.4.0"
authors = ["paul@colomiets.name"]

[dependencies]
mio = "0.5"

[dev-dependencies]
argparse = "0.2.1"
nix = "0.4.2"

[lib]
name = "rotor"
path = "src/lib.rs"

